### ISSUE TITLE
Unable to access jarfile build\libs\ukulele.jar

### ISSUE THREAD

**Issue by amadejhp** [freyacodes/ukulele#21]
Jarfile in build\libs\ukulele.jar does not exist, where could I acquire it?
I would just like to locally set this up as a music bot without any modifications or changes, just simple use. I'm using Windows 10.
![image](https://user-images.githubusercontent.com/25230774/133515391-c50862cf-3047-474a-929f-6f87a6dae7b4.png)

**Comment by OtterBoops** [comment]
You don't have JRE installed.

**Comment by amadejhp** [comment]
Thank you, I will try installing it
