### ISSUE TITLE
How to invite the bot to a server

### ISSUE THREAD

**Issue by amadejhp** [freyacodes/ukulele#22]
I think that it works now, how would I invite the bot to the server?
![image](https://user-images.githubusercontent.com/25230774/133517269-7f25daaf-a130-46ce-9326-070b3000ab35.png)

**Comment by OtterBoops** [comment]
You should try reading the readme of this repo. You have asked two questions that already have an answer there.
https://discordjs.guide/preparations/setting-up-a-bot-application.html
