### ISSUE TITLE
:compileKotlin Failed

### ISSUE THREAD

**Issue by SleepySharkie** [freyacodes/ukulele#24]
Hi, i tried to run ukulele with .bat file, and it fails at :compileKotlin for some reason

It says that it can't find required JDK tools ( which i have no clue what does it mean )

So, if someone know how to fix it, please reply thanks <3
![image](https://user-images.githubusercontent.com/83663950/133894608-da987b9a-d1a1-48d8-972c-f017355f1143.png)

**Comment by OtterBoops** [comment]
Install JDK.
