### ISSUE TITLE
Accessing the queue database

### ISSUE THREAD

**Issue by skyventuree** [freyacodes/ukulele#30]
How do I access the queue database? I need them for another bot that handle another stuff (will be written in another language as I am not good at Java.)

**Comment by OtterBoops** [comment]
The queue is not stored in a database.

**Comment by skyventuree** [comment]
Is there anyway that I could access the queue?

**Comment by freyacodes** [comment]
If you really insist and want to get your hands dirty you could implement a simple REST API.

**Comment by skyventuree** [comment]
Thanks for the advice!
